name: xcmobile
description: "A new Flutter project."
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.2.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  intl: #datetime
  path_provider: ^2.1.3

  #UI
  cupertino_icons: ^1.0.2
  google_fonts: 6.1.0
  wolt_modal_sheet:
  cached_network_image:
  animate_do:
  flutter_riverpod:
  top_snackbar_flutter: ^3.1.0
  pinput:
  lottie: ^3.1.0

  #Scanner
  mobile_scanner: ^4.0.1

  google_ml_text_recognizer: ^0.0.3
  google_mlkit_text_recognition: ^0.8.1
  image_picker: ^1.0.0
  mrz_parser: ^2.0.0
  camera: ^0.10.5+9
  #flutter_mrz_scanner: ^2.1.0
  #mrz_scanner: ^0.0.1+3
  #flutter_scan_tools: ^0.0.3


  #Networking
  http: #fetching
  connectivity_plus:

  #phone information
  package_info_plus: 
  permission_handler: ^10.2.0
  sim_data_plus: ^0.1.4
  screenshot: ^2.3.0

  #Storage
  hive: 
  hive_flutter: 

  #Security
  local_auth: ^2.2.0
  local_auth_android: ^1.0.37
  local_auth_darwin: ^1.2.2

  firebase_core:
  

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0


flutter:


  uses-material-design: true

  assets:
    - assets/
    - assets/images/
    - assets/logos/
    - assets/animated/
